### GET
GET http://localhost/rebilly/get
    ?param=param-from-get

### POST
POST http://localhost/rebilly/post
Content-Type: application/json

{
	"param": "param-from-post"
}

### invoices
POST http://localhost/rebilly/invoices

### deposit-with-strategy
POST http://localhost/rebilly/deposit-with-strategy
Content-Type: application/json

{
	"currency": "USD",
	"strategyId": "dep_str_01JAZR9M6QEB792433FNEQKCTV"
}
